spring:
  application:
    name: Config-Default
      eureka:
        instance:
          prefer-ip-address: true
        client:
          register-With-Eureka: true
          fetchRegistry: true
          service-url:
            defaultZone: http://localhost:8761/eureka

            
spring.cloud.config.server.git.default-label= main
